version: 2
checks:
  argument-count:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  duplication:
    enabled: true

plugins:
  pylint:
    enabled: true
    channel: "latest"
  flake8:
    enabled: true
  fixme:
    enabled: true
